name: Docker Image CI

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PLATFORMS: |
    linux/arm/v7
    linux/arm64
    linux/amd64
  TAGS: |
    type=schedule
    type=ref,event=branch
    type=ref,event=tag
    type=ref,event=pr
    type=sha,prefix=,suffix=,format=long

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup deps
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to DockerHub
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Collect image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: ${{ env.TAGS }}
      - name: Build and push release
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.actor == github.repository_owner }}
          load: ${{ github.actor != github.repository_owner }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            ${{ github.repository }}-cache
          cache-to: |
            type=registry,ref=${{ github.repository }}-cache,mode=max
          platforms: ${{ env.PLATFORMS }}
      - name: Test image
        run: docker run --rm ${GITHUB_REPOSITORY}:${GITHUB_SHA} -v
